### ISSUE TITLE
Json格式问题

### ISSUE THREAD

**Issue by liangtj** [Binly42/agenda-go2#4]
Json正确格式中，(子)对象内最后一个字段后不要加 ","(逗号)

**Comment by liangtj** [comment]
不仅仅是对象，数组也一样，最后一个键值对不要+逗号

**Comment by Binly42** [comment]
我记得*比较新的标准*好像已经可以这样了吧, 我当时是先用 普通的版本的, 发现加上了逗号那个 API Blueprint 也不会有验证错误, 就全给加上了 ; (也可能只是它们家的扩展吧, 管他)

你有碰到问题了?

**Comment by liangtj** [comment]
你加个逗号，坑到我了尼玛 @Binly42

**Comment by Binly42** [comment]
所以 ... 到底是什么坑啊 ? ... ( 实在不行你就给编辑掉呗 ...

**Comment by liangtj** [comment]
就是本地Decode的时候会不断的提示找不到 { 啊等等

**Comment by Binly42** [comment]
我还以为 Go 既然都支持(甚至鼓励)尾部逗号, 就不会有这种问题的 ...

**Comment by liangtj** [comment]
求求你快点，看，，，，，看寶石の國
